apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-production-e2e-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complete-production-e2e-app
  template:
    metadata:
      labels:
        app: complete-production-e2e-app
    spec:
      containers:
      - name: complete-production-e2e-app
        image: jinjia/complete-production-e2e-pipeline:1.0.0-9
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
        ports:
        - containerPort: 8080