apiVersion: v1
kind: Service
metadata:
  name: complete-production-e2e-deployment-service
spec:
  selector:
    app: complete-production-e2e-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080